name: Build manually

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Metadata tag. Use test for a date-based dev build.
        required: false
        default: test
      windows:
        description: Build Windows x64 and arm64
        type: boolean
        required: true
        default: true
      macos:
        description: Build macOS arm64
        type: boolean
        required: true
        default: true

jobs:
  windows:
    name: Build Windows x64 and arm64
    if: inputs.windows
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Create metadata
        run: npm run make --tag="${{ inputs.tag }}"

      - name: Build renderer and electron
        run: npm run build:vite

      - name: Build Windows packages
        run: node builder.cjs --win32=x64,arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: windows-x64-arm64
          path: release/**

  macos:
    name: Build macOS arm64
    if: inputs.macos
    runs-on: macos-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Create metadata
        run: npm run make --tag="${{ inputs.tag }}"

      - name: Build renderer and electron
        run: npm run build:vite

      - name: Build macOS package
        run: node builder.cjs --darwin=arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: macos-arm64
          path: release/**
